USE [master]
GO

/****** Object:  Database [ColorMeRGB]    Script Date: 4/18/2022 5:41:13 PM ******/
CREATE DATABASE [ColorMeRGB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ColorMeRGB', FILENAME = N'C:\Users\sebas\ColorMeRGB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ColorMeRGB_log', FILENAME = N'C:\Users\sebas\ColorMeRGB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ColorMeRGB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ColorMeRGB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ColorMeRGB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ColorMeRGB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ColorMeRGB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ColorMeRGB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ColorMeRGB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ColorMeRGB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ColorMeRGB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ColorMeRGB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ColorMeRGB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ColorMeRGB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ColorMeRGB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ColorMeRGB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ColorMeRGB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ColorMeRGB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ColorMeRGB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ColorMeRGB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ColorMeRGB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ColorMeRGB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ColorMeRGB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ColorMeRGB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ColorMeRGB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ColorMeRGB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ColorMeRGB] SET  MULTI_USER 
GO

ALTER DATABASE [ColorMeRGB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ColorMeRGB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ColorMeRGB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ColorMeRGB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ColorMeRGB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ColorMeRGB] SET QUERY_STORE = OFF
GO

USE [ColorMeRGB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [ColorMeRGB] SET  READ_WRITE 
GO

